// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// corr_groups_from_corr_cpp
Rcpp::IntegerVector corr_groups_from_corr_cpp(const Rcpp::NumericMatrix& corr, double cutoff);
RcppExport SEXP _costablr_corr_groups_from_corr_cpp(SEXP corrSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type corr(corrSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_groups_from_corr_cpp(corr, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// mvr_solve_ungrouped_cpp
arma::mat mvr_solve_ungrouped_cpp(const arma::mat& Sigma, int num_iter, double smoothing, double converge_tol, bool verbose, Rcpp::Nullable<Rcpp::IntegerMatrix> update_order);
RcppExport SEXP _costablr_mvr_solve_ungrouped_cpp(SEXP SigmaSEXP, SEXP num_iterSEXP, SEXP smoothingSEXP, SEXP converge_tolSEXP, SEXP verboseSEXP, SEXP update_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< double >::type smoothing(smoothingSEXP);
    Rcpp::traits::input_parameter< double >::type converge_tol(converge_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerMatrix> >::type update_order(update_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(mvr_solve_ungrouped_cpp(Sigma, num_iter, smoothing, converge_tol, verbose, update_order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_costablr_corr_groups_from_corr_cpp", (DL_FUNC) &_costablr_corr_groups_from_corr_cpp, 2},
    {"_costablr_mvr_solve_ungrouped_cpp", (DL_FUNC) &_costablr_mvr_solve_ungrouped_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_costablr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
