# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corr_groups_from_corr_cpp <- function(corr, cutoff) {
    .Call(`_costablr_corr_groups_from_corr_cpp`, corr, cutoff)
}

mvr_solve_ungrouped_cpp <- function(Sigma, num_iter = 50L, smoothing = 0.0, converge_tol = 1e-3, verbose = FALSE, update_order = NULL) {
    .Call(`_costablr_mvr_solve_ungrouped_cpp`, Sigma, num_iter, smoothing, converge_tol, verbose, update_order)
}

